export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';

export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';

export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';

export const INCREMENT_PAGE = 'INCREMENT_PAGE';

export const EMPTY_PRODUCTS_LIST = 'EMPTY_PRODUCTS_LIST';

export const SET_HAS_MORE_PRODUCTS = 'SET_HAS_MORE_PRODUCTS';


